name: Build Debian Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install dpkg ldid make

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Build .deb package
        run: |
          make clean package
        env:
          THEOS: ${{ env.THEOS }}

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: jailbreak-deb
          path: packages/*.deb
